
spring:
  profiles:
    active:
    - product

security:
    user:
      name: user
      password: test
    oauth2:
      client:
        client-id: foo
        client-secret: bar    



   

 
--- 
server:
  port: 8080

spring:

  
  profiles: dev




 
  datasource:
    url: jdbc:mysql://localhost:3306/arachne_db?useSSL=false
    username: ksr_arachne_dev
    password: arachne_password
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
  
  redis:
    port: 6379 
    host: www.ksr.pe.kr
    password: 1234 
  
  session:
    store-type: redis  
    
    
---

 

server:
  port: 8082  
  
spring:

  
  profiles: product




 
  datasource:
    url: jdbc:mysql://arachnedatabase.cpmqq8pzapbm.ap-northeast-2.rds.amazonaws.com:3306/arachne_db?useSSL=false
    username: sky5367
    password: rlatjduf510
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
  
  redis:
    port: 6379 
    host: www.ksr.pe.kr
    password: 1234 
  
  session:
    store-type: redis  
        
    
 